name: do_an_tot_nghiep
description: A Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_screenutil: ^5.7.0
  flutter_localizations: 
    sdk: flutter
  hive: ^2.2.3
  http: ^0.13.6
  path_provider: ^2.0.15
  provider: ^6.0.5
  flutter_staggered_animations: ^1.1.1
  tuple: ^2.0.2
  fl_chart: ^0.64.0
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.12.2
  flutter_switch: ^0.3.2
  flutter_easyloading: ^3.0.5
  flutter_facebook_auth: ^5.0.11
  cached_network_image: ^3.3.0
  audioplayers: ^5.2.1
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0
  change_app_package_name: ^1.1.0
  build_runner: ^2.4.6
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launcher_icon.png"
flutter_native_splash:
  color: '#19212E'
  android_12:
    color: '#19212E'
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/default_cards/
    - assets/images/shape/
    - assets/audio/
  fonts:
    - family:  CustomIcon
      fonts:
       - asset: assets/fonts/CustomIcon.ttf
    - family: SofiaPro
      fonts:
        - asset: assets/fonts/SofiaProRegular.otf
        - asset: assets/fonts/SofiaProBold.otf
          weight: 700
        - asset: assets/fonts/SofiaProExtraLight.otf
          weight: 200
flutter_intl:
  enabled: true
